Nomenclatures.Web/Controllers/FamilleMatierePremiereController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nomenclatures.Data;
using Nomenclatures.Web.Models;

namespace Nomenclatures.Web
{
    public class FamilleMatierePremiereController
        : Controller
    {
        private NomenclaturesContext _dbContext;
        private const int cstPageSize = 10;

        public FamilleMatierePremiereController(NomenclaturesContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult List(int pageIndex)
        {
            return View(_dbContext.FamillesPremieres
                .OrderBy(f => f.Nom)
                .Skip(pageIndex * cstPageSize)
                .Take(cstPageSize));
        }

        public IActionResult Edit(int id)
        {
            var f = _dbContext.FamillesPremieres.Find(id);
            if (f == null) return NotFound();

            return View(f);
        }

        public IActionResult Create()
        {
            return View(nameof(Edit), new Nomenclatures.Data.FamilleMatierePremiere());
        }

        public IActionResult Delete(int id)
        {
            var f = _dbContext.FamillesPremieres.Find(id);
            if (f != null)
            {
                _dbContext.FamillesPremieres.Remove(f);
                _dbContext.SaveChanges();
            }

            return RedirectToAction(nameof(List));
        }

        [HttpPost]
        public IActionResult Save(Nomenclatures.Data.FamilleMatierePremiere f)
        {
            if (f.Id != 0)
            {
                _dbContext.Attach(f).State = EntityState.Modified;
            }
            else
            {
                _dbContext.FamillesPremieres.Add(f);
            }

            _dbContext.SaveChanges();

            return RedirectToAction(nameof(List));
        }
    }
}

Nomenclatures.Web/Controllers/MatierePremiereController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Nomenclatures.Data;
using Nomenclatures.Web.Models;

namespace Nomenclatures.Web
{
    public class MatierePremiereController
        : Controller
    {
        private NomenclaturesContext _dbContext;
        private const int cstPageSize = 10;

        public MatierePremiereController(NomenclaturesContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult List(int pageIndex)
        {
            return View(_dbContext.MatieresPremieres
                .Include(mp => mp.Famille)
                .OrderBy(mp => mp.Nom)
                .Skip(pageIndex * cstPageSize)
                .Take(cstPageSize));
        }

        public IActionResult Edit(int id)
        {
            var mp = _dbContext.MatieresPremieres.Find(id);
            if (mp == null) return NotFound();

            return View(new MatierePremiereViewModel(mp, _dbContext.FamillesPremieres.OrderBy(fmp => fmp.Nom)));
        }

        public IActionResult Create()
        {
            return View(nameof(Edit), new MatierePremiereViewModel(_dbContext.FamillesPremieres.OrderBy(fmp => fmp.Nom)));
        }

        public IActionResult Delete(int id)
        {
            var mp = _dbContext.MatieresPremieres.Find(id);
            if (mp != null)
            {
                _dbContext.MatieresPremieres.Remove(mp);
                _dbContext.SaveChanges();
            }

            return RedirectToAction(nameof(List));
        }

        [HttpPost]
        public IActionResult Save(Nomenclatures.Data.MatierePremiere mp)
        {
            if (ModelState.IsValid)
            {
                if (mp.Id != 0)
                {
                    _dbContext.Attach(mp).State = EntityState.Modified;
                }
                else
                {
                    _dbContext.MatieresPremieres.Add(mp);
                }

                _dbContext.SaveChanges();
            }

            return RedirectToAction(nameof(List));
        }
    }
}

Nomenclatures.Web/Controllers/ProduitController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nomenclatures.Data;
using Nomenclatures.Web.Models;

namespace Nomenclatures.Web
{
    public class ProduitController : Controller
    {
        private NomenclaturesContext _dbContext;
        private const int cstPageSize = 10;

        public ProduitController(NomenclaturesContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult List(int pageIndex)
        {
            var types = typeof(Produit).Assembly
                .GetTypes().Where(t => t.BaseType == typeof(Produit))
                .OrderBy(t => t.Name);

            return View(((IEnumerable<Nomenclatures.Data.Produit>)_dbContext.Produits
                .OrderBy(f => f.Nom)
                .Skip(pageIndex * cstPageSize)
                .Take(cstPageSize)
                .Select(p => p), (IEnumerable<Type>)types));
        }

        public IActionResult Edit(int id)
        {
            var p = _dbContext.Produits
                .Include(p => p.Composants)
                    .ThenInclude(c => c.MP)
                .Include(p => p.Composants)
                    .ThenInclude(c => c.PSF)
                .FirstOrDefault(prd => prd.Id == id);
            if (p == null) return NotFound();

            return View(nameof(Edit) + p.GetType().Name, p);
        }

        [HttpPost]
        public IActionResult Create(string type)
        {
            return View(nameof(Edit) + type, 
                typeof(Produit).Assembly
                    .GetType($"Nomenclatures.Data.{type}")
                    .GetConstructor(new Type[]{})
                    .Invoke(null));
        }

        public IActionResult Delete(int id)
        {
            var p = _dbContext.Produits.Find(id);
            if (p != null)
            {
                _dbContext.Produits.Remove(p);
                _dbContext.SaveChanges();
            }

            return RedirectToAction(nameof(List));
        }

        [HttpPost]
        public IActionResult SaveProduitFini(Nomenclatures.Data.ProduitFini p)
        {
            PrepareSave(p);
            return Save(p, new ProduitFini(p));
        }

        [HttpPost]
        public IActionResult SaveProduitSemiFini(Nomenclatures.Data.ProduitSemiFini p)
        {
            PrepareSave(p);
            return Save(p, new ProduitSemiFini(p));
        }

        private IActionResult Save(Nomenclatures.Data.Produit p, Nomenclatures.Produit produitDomain)
        {
            if (ModelState.IsValid)
            {
                if (!produitDomain.IsValid)
                {
                    foreach (var me in produitDomain.GetErrors())
                        ModelState.AddModelError(me.Property, me.Message);

                    return View("Edit" + p.GetType().Name, p);
                }

                _dbContext.SaveChanges();

                return RedirectToAction(nameof(List));
            }

            return View("Edit" + p.GetType().Name, p);
        }

        private void PrepareSave(Nomenclatures.Data.Produit p)
        {
            foreach (var key in Request.Form.Keys)
            {
                if (key.StartsWith("comp_qty"))
                {
                    var index = key.Substring("comp_qty".Length);
                    var idc = Convert.ToInt32(Request.Form["comp_idc" + index]);
                    var id = Convert.ToInt32(Request.Form["comp_id" + index]);
                    var qty = Convert.ToInt32(Request.Form["comp_qty" + index]);
                    var type = Request.Form["comp_type" + index];

                    Data.ComponentQty cpqty = null;
                    if (type == "ProduitSemiFini")
                    {
                        cpqty = new Data.ComponentQty
                        {
                            Id = idc,
                            Qty = qty,
                            PSF = _dbContext.ProduitsSemiFinis.Find(id)
                        };
                    }
                    else
                    {
                        cpqty = new Data.ComponentQty
                        {
                            Id = idc,
                            Qty = qty,
                            MP = _dbContext.MatieresPremieres.Find(id)
                        };
                    }

                    p.Composants.Add(cpqty);

                    if (cpqty.MP != null)
                        _dbContext.Attach(cpqty.MP).State = EntityState.Unchanged;
                    else
                        _dbContext.Attach(cpqty.PSF).State = EntityState.Unchanged;

                    if (idc != 0)
                        _dbContext.Attach(p.Composants.Last()).State = EntityState.Modified;
                }
            }            

            if (p.Id != 0)
            {
                _dbContext.Attach(p).State = EntityState.Modified;
            }
            else
            {
                _dbContext.Produits.Add(p);
            }
        }

        public IActionResult AugmentationPU()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AugmentationPU(AugmentationPrixProduitViewModel appv)
        {
            var cmd = new AugmentationPrixProduit(_dbContext);
            cmd.PourcentageAugmentation = appv.PourcentageAugmentation;
            cmd.Execute();

            return RedirectToAction(nameof(List));
        }
    }
}

Nomenclatures.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nomenclatures</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nomenclatures</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Page d'accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MatierePremiere" asp-action="List">Matières premières</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FamilleMatierePremiere" asp-action="List">Familles matières premières</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produit" asp-action="List">Produits</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Nomenclatures.Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>